WIP: NixOS

diff --git a/.config/my/deploy-setup/hooks/prepare-home b/.config/my/deploy-setup/hooks/prepare-home
--- a/.config/my/deploy-setup/hooks/prepare-home
+++ b/.config/my/deploy-setup/hooks/prepare-home
@@ -26,8 +26,35 @@ function change-gitignore
 }
 
 
-if [ "${MY_PLATFORM_VARIANT:-}" != NixOS ]
+function prepare-home-manager
+{
+    # This only prepares the channel.  Home Manager is later installed by
+    # ~/.local/share/my/platform/Linux/NixOS/packages.bash (typically by ./install-packages by
+    # ~/.local/share/my/deploy-setup/bootstrap/start1.bash).
+
+    [[ "$(nixos-version)" =~ ^([[:digit:]]+\.[[:digit:]]+) ]]  # errexit on fail
+    local -r nixOSver=${BASH_REMATCH[1]}
+    local -r repo=https://github.com/nix-community/home-manager
+    local -r URL=$repo/archive/release-$nixOSver.tar.gz
+
+    nix-channel --add "$URL" home-manager
+    nix-channel --update home-manager
+}
+
+function prepare-nixos-unstable
+{
+    local -r URL=https://nixos.org/channels/nixos-unstable
+
+    nix-channel --add "$URL" nixos-unstable
+    nix-channel --update nixos-unstable
+}
+
+
+if [ "${MY_PLATFORM_VARIANT-}" = NixOS ]
 then
+    prepare-home-manager
+    prepare-nixos-unstable
+else
     # Change .gitignore to not ignore files that are of interest in the target home.
     #
     change-gitignore || warn 'Failed to change .gitignore.'
